server:
  port: 8080

logging:
  path: ./log/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apple?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: Letmein123$%^
    driver-class-name: com.mysql.cj.jdbc.Driver

debug: false
